### ISSUE TITLE
Meetings table

### ISSUE THREAD

**Issue by carduz** [dsd-meetme/backend#18]
I think that a better structure for the table can be the following:
TimeSlotsAvailable = Array()
Duration = Int
StartTimeSlot -> null if the meeting is not planed yet
TimeSlots can be the structure that contains the timeslots that I have explained on the optimisation document, even if we have a big overhead in this way

what do you think @Mihica @Emil-Sila ?

**Comment by Mihica** [comment]
Yeah, I agree. The current structure was made without timeslots in mind anyway. 

```
On Thursday, December 10, 2015 12:33 AM, claudio cardinale <notifications@github.com> wrote:
```

 I think that a better structure for the table can be the following:
TimeSlotsAvailable = Array()
Duration = Int
StartTimeSlot -> null if the meeting is not planed yet
TimeSlots can be the structure that contains the timeslots that I have explained on the optimisation document, even if we have a big overhead in this waywhat do you think @Mihica @Emil-Sila ?—

**Comment by carduz** [comment]
ok, so who makes this?

**Comment by carduz** [comment]
done
