### ISSUE TITLE
caldav UTC or GMT?

### ISSUE THREAD

**Issue by carduz** [dsd-meetme/backend#7]

**Comment by Emil-Sila** [comment]
UTC, GMT is a timezone and UTC is a standard.

**Comment by carduz** [comment]
no  
UTC = universal time zone  
GMT = Greenwich time

Take a look https://www.google.it/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8&client=ubuntu#q=utc+gmt+difference

they have the same time, but I don't remember if there are differences, maybe GMT has DST, but I'm not sure. I have to check, but I have not time now, so I put this issue ;)

**Comment by Emil-Sila** [comment]
"Greenwich Mean Time (GMT) is often interchanged or confused with Coordinated Universal Time (UTC). But GMT is a time zone and UTC is a time standard."

And no, UTC does not have DST
